fix: update celery and libsass versions celery version needs to updated due to below error ``` 1.512   File "/openedx/ecommerce/ecommerce/extensions/offer/utils.py", line 15, in <module> 1.513     from ecommerce_worker.email.v1.api import send_offer_assignment_email, send_offer_update_email 1.513   File "/openedx/venv/lib/python3.12/site-packages/ecommerce_worker/email/v1/api.py", line 7, in <module> 1.513     from .tasks import ( 1.513   File "/openedx/venv/lib/python3.12/site-packages/ecommerce_worker/email/v1/tasks.py", line 6, in <module> 1.514     from celery import shared_task 1.514   File "/openedx/venv/lib/python3.12/site-packages/celery/__init__.py", line 19, in <module> 1.514     from . import local  # noqa 1.514     ^^^^^^^^^^^^^^^^^^^ 1.514   File "/openedx/venv/lib/python3.12/site-packages/celery/local.py", line 17, in <module> 1.515     from .five import PY3, bytes_if_py2, items, string, string_t 1.515   File "/openedx/venv/lib/python3.12/site-packages/celery/five.py", line 7, in <module> 1.515     import vine.five 1.515   File "/openedx/venv/lib/python3.12/site-packages/vine/__init__.py", line 8, in <module> 1.515     from .abstract import Thenable 1.515   File "/openedx/venv/lib/python3.12/site-packages/vine/abstract.py", line 6, in <module> 1.516     from .five import with_metaclass, Callable 1.516   File "/openedx/venv/lib/python3.12/site-packages/vine/five.py", line 364, in <module> 1.516     from inspect import formatargspec, getargspec as _getargspec  # noqa 1.516     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 1.517 ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/pyenv/versions/3.12.2/lib/python3.12/inspect.py). Did you mean: 'formatargvalues'? ``` libsass version needs to updated due to below error ``` 1.603   File "/openedx/ecommerce/ecommerce/theming/management/commands/update_assets.py", line 7, in <module> 1.604     import sass 1.604   File "/openedx/venv/lib/python3.12/site-packages/sass.py", line 609, in <module> 1.604     class SassMap(collections.Mapping): 1.604                   ^^^^^^^^^^^^^^^^^^^ 1.604 AttributeError: module 'collections' has no attribute 'Mapping' ```