fix: pin pytest-selenium & pytest-variables to v2
There is a dependency conflict for pytest in pytest-selenium v3, which conflictingly requires both:

- pytest v6:

https://github.com/pytest-dev/pytest-selenium/blob/8e0a5d549049a1db353ead98bf0b46f8ef04e014/pyproject.toml#L46

- pytest-metadata latest (via pytest-html), whose latest 3.0.0 requires pytest v7:

https://github.com/pytest-dev/pytest-metadata/blob/4f70f2ae74dc880772d445b1ee2cbe8d50bedcbd/pyproject.toml#L43

Pin pytest-selenium to v2 for now.

This resolves `make upgrade` error:

    There are incompatible versions in the resolved dependencies:
      pytest (from -r requirements/e2e.in (line 6))
      pytest<7.0.0,>=6.0.0 (from pytest-selenium==3.0.0->-r requirements/e2e.in (line 8))
      pytest>=2.4.2 (from pytest-variables==1.9.0->pytest-selenium==3.0.0->-r requirements/e2e.in (line 8))
      pytest>=7.0.0 (from pytest-metadata==3.0.0->pytest-html==3.2.0->pytest-selenium==3.0.0->-r requirements/e2e.in (line 8))
      pytest>=5.0.0 (from pytest-timeout==2.1.0->-r requirements/e2e.in (line 9))
      pytest>=2.7.3 (from pytest-base-url==1.4.2->pytest-selenium==3.0.0->-r requirements/e2e.in (line 8))
      pytest (from pytest-randomly==3.12.0->-r requirements/e2e.in (line 7))
      pytest!=6.0.0,>=5.0 (from pytest-html==3.2.0->pytest-selenium==3.0.0->-r requirements/e2e.in (line 8))

See https://github.com/pytest-dev/pytest-selenium/issues/294 for potential upstream issue.

Also, pytest-variables v3 deprecated _variables, which is used by other pytest v2 libraries::

https://github.com/pytest-dev/pytest-variables/blob/13f4b2e4620c682ae0856e03b11106ad3b6e6894/CHANGES.rst

Pin pytest-variables to v2 for now.

This resolves `make acceptance` error:

    AttributeError: 'Config' object has no attribute '_variables'